[package]
name = "avantis-utils"
description = "Swiss army knife utilities for all kind of Avantis rust projects"
authors = ["Avantis - Genesis <it-be-avantis@ava.fund>"]
homepage = "https://github.com/ava-global/avantis-rust-utilities"
repository = "https://github.com/ava-global/avantis-rust-utilities"
license = "MIT"
version = "0.2.0"
edition = "2021"
readme = "README.md"
keywords = ["utility"]

[dependencies]
config = { version = "0.13", optional = true }
strum = { version = "0.24", features = ["derive"], optional = true }
serde = { version = "1.0", optional = true }
anyhow = { version = "1.0", optional = true }
sqlx = { version = "0.5", features = ["postgres", "runtime-tokio-rustls"], optional = true }
redis = { version = "0.21.5",  features = ["cluster"]}
bb8-redis = "0.11.0"
async-trait = "0.1.53"
tokio = { version = "1.17.0",  features = ["full"]}
tracing = "0.1.33"

[dev-dependencies]
mocktopus = "0.7.11"
once_cell = "1.0"

[features]
default = ["cfg", "db"]
cfg = ["config", "strum", "serde", "anyhow"]
db = ["sqlx", "serde"]
