[package]
name = "avantis-rust-utilities"
authors = ["Avantis - Genesis"]
version = "0.1.0"
edition = "2021"

[lib]
name = "avantis_utils"

[dependencies]
config = { version = "0.12", optional = true }
strum = { version = "0.24", features = ["derive"], optional = true }
serde = { version = "1.0", optional = true }
anyhow = { version = "1.0", optional = true }

[features]
default = ["cfg"]
cfg = ["config", "strum", "serde", "anyhow"]
