[package]
name = "avantis-rust-utilities"
description = "Swiss army knife utilities for all kind of Avantis rust projects"
authors = ["Avantis - Genesis"]
homepage = "https://github.com/ava-global/avantis-rust-utilities"
repository = "https://github.com/ava-global/avantis-rust-utilities"
license = "MIT"
version = "0.1.0"
edition = "2021"
readme = "README.md"
keywords = ["utility"]

[lib]
name = "avantis_utils"

[dependencies]
config = { version = "0.12", optional = true }
strum = { version = "0.24", features = ["derive"], optional = true }
serde = { version = "1.0", optional = true }
anyhow = { version = "1.0", optional = true }

[features]
default = ["cfg"]
cfg = ["config", "strum", "serde", "anyhow"]
