db:
  host: localhost
  user: username
  password: REPLACE_ME
  db_name: my_db
  max_connections: 30

redis:
  hosts_csv: "redis://avantis-redis-dev-5295a48.3o3tur.clustercfg.apse1.cache.amazonaws.com:6379, redis://avantis-redis-dev-5295a48.3o3tur.clustercfg.apse1.cache.amazonaws.com:6379"
  max_connections: 2
  expire_seconds: 1

kafka:
  brokers_csv: "REPLACE_WITH_KAFKA_URL1,REPLACE_WITH_KAFKA_URL2,REPLACE_WITH_KAFKA_URL3"
  flush_duration_millis : 10000
  poll_duration_millis: 1
  security_protocol: "ssl"